services:  
  pg:
    container_name: pg_container
    build: ./postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
    ports:
    - "5432:5432"
    volumes:
    - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
